gradle.properties, src/main/resources/fabric.mod.json
(I wanted to use this library to create a shield for my own mod, which is work in progress. But I saw that the library wasn't up to date yet).
I changed the versions to a 1.16.1 and quickly tested if it would boot up. Can you double check and publish it @CrimsonDawn45 ?
Also I saw a test_enchantment and basic_shield being initialized, is that supposed to happen to? Because that would be published in the Library as well.
Thanks in advance!
=> Version bump to 1.16.1

src/main/java/me/crimsondawn45/fabricshieldlib/FabricShieldLib.java
This PR wraps all test content in a development environment check. Fixes #7.
=> Add dev check to test items/events/enchantments

src/main/java/me/crimsondawn45/fabricshieldlib/object/TestEvent.java
Might be a better idea to just get rid of all test related code (since they only affect the vanilla shield anyways) but this should at least get rid of the spam from #10.
=> Comment out spam log

src/main/java/me/crimsondawn45/fabricshieldlib/mixin/PlayerEntityMixin.java
Fix the damageShield and possibly disableShield (altho I haven't tested disableShield) mixins not firing due to incorrect injection points.
I can't seem to see why it was set to TAIL, but setting it to HEAD doesn't seem to break anything 🤷
=> Fix some mixins not firing

src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldBannerRendering.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLibClient.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/RendererMixin.java, src/main/resources/fabric.mod.json
it was apparently not needed in 1.14. I moved the renderBanner method to a plain class and renamed it render, with the class being called FabricShieldBannerRendering
=> deleted client init (1.14)

src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLibClient.java
Reverts CrimsonDawn45/Fabric-Shield-Lib#67
=> Revert "removed unneeded code in client init(1.16)"

src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLibClient.java
Reverts CrimsonDawn45/Fabric-Shield-Lib#68
=> Revert "removed unneeded code in client init (1.15)"

src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLibClient.java
Reverts CrimsonDawn45/Fabric-Shield-Lib#69
=> Revert "removed unneeded code in client init (1.17)"

src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLibClient.java
Reverts CrimsonDawn45/Fabric-Shield-Lib#65
=> Revert "removed unneeded code in client init(1.18)"

README.md, build.gradle, gradle.properties, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricBannerShieldItem.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldItem.java
i added missing imports for a few classes and updated gradle.properties to work 1.19+
also updated readme
=> updated gradle.properties and imported missing things, now ready for 1.19

src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLib.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/LivingEntityMixin.java
The bug was that the block event wasn't being invoked
=> Split @Inject inside LivingEntityMixin to fix bug

src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLib.java
By checking if the shield actually blocked damage, the reflection enchantment works properly now, fixing issue #105.
=> Fixed #105

build.gradle, src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLib.java
having crowdlin as a modImplementation messed things up.pushing this for new release
=> EMERGENCY BUG FIX

src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLibClient.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/config/FabricShieldLibConfig.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/config/FabricShieldLibModMenuIntegration.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/core/EnchantmentTargetMixin.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/core/ShieldEnchantmentTarget.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/event/ShieldBlockCallback.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/event/ShieldDisabledCallback.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricBannerShieldItem.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShield.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldDecoratorRecipe.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldEnchantment.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldItem.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/RepairItemType.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/RepairType.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/LivingEntityAccessor.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/LivingEntityMixin.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/PlayerEntityMixin.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/RendererMixin.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/ShieldItemMixin.java
**Contains;**
- Reformates code,
- Reduces duplicates,
- Adjusts whitespaces.
=> Refactor code

build.gradle, gradle.properties, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/config/FabricShieldLibConfig.java, src/main/resources/assets/fabricshieldlib/lang/en_us.json, src/main/resources/assets/fabricshieldlib/lang/fr_fr.json, src/main/resources/assets/fabricshieldlib/lang/ru_ru.json
Fixed boot loop issue #127  by removing crowdlin, fixed lang files, and added Russian translations
=> Fixed  #127, added Russian translation

build.gradle, gradle.properties
updated dependency and mod versions so that I can release 1.7
=> updated versions for 1.7 release

README.md, gradle.properties
Specified that this specific version is for 1.19.3, and fixed the version in the readme and removed the translations section as we don't use crowdlin anymore
=>  Updated versions for 1.7 relelase, fixed readme

gradle.properties
messed up on versions, fixed it again
=> fixed versions

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLib.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLibClient.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricBannerShieldItem.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldDecoratorRecipe.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldItem.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/LivingEntityMixin.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/PlayerEntityMixin.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/RendererMixin.java, src/main/resources/fabric.mod.json
Finally updated to this version.
fixes: #151
=> Updated to 1.20.2

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/resources/data/c/tags/items/shields.json
fixed some of the bugs, updated dependencies
fixes: #143, #148
=> Updated 1.17.1

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLib.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLibClient.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricBannerShieldItem.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldDecoratorRecipe.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldItem.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/LivingEntityMixin.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/RendererMixin.java
fixed some of the bugs, updated dependencies
fixes: #143 #148
=> Updated to 1.19.4

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLib.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/PlayerEntityMixin.java, src/main/resources/data/c/tags/items/shields.json
fixed some of the bugs, updated dependencies, made it work with the official c:shields
fixes: #147 #148 #149 #146 #143
=> Updated 1.18.2

build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLib.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/initializers/FabricShieldLibClient.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricBannerShieldItem.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldItem.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/LivingEntityMixin.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/PlayerEntityMixin.java, src/main/java/com/github/crimsondawn45/fabricshieldlib/mixin/RendererMixin.java, src/main/resources/data/c/tags/items/shields.json
fixed some of the bugs, updated dependencies
fixes: #148 #143
=> Updated 1.19.2

README.md, src/main/resources/fabric.mod.json
just adding OverLordsIII to the contributors list
=> Update contributors & Readme for 1.20

README.md, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/resources/assets/fabricshieldlib/lang/uk_ua.json, src/main/resources/data/c/tags/items/shields.json, src/main/resources/fabric.mod.json
- Updated dependencies (#162)
- Updated Gradle
- Fixed the C: shields bug #164 
- Update mod version to 1.7.2
- Added Ukrainian translation (thanks SKZGx)
=> Updated 1.19.4

gradle.properties, src/main/java/com/github/crimsondawn45/fabricshieldlib/lib/object/FabricShieldDecoratorRecipe.java
So apparently there was a different line of code that messed up 1.20.2 versions' compatibility with 1.20.1
This version will support 1.20 and 1.20.1
The main branch will be 1.20.2-1.20.4
=> Did backport for 1.20.1

gradle.properties
Just updated our dependencies and versions, I dont think theres a need to move up a mod version.
=> Updated to 1.20.4
